import requests
import pandas as pd
import schedule
import time
from datetime import datetime

# Replace with your CoinGecko API Key
API_KEY = "CG-MfMJsvzUhR8PtJfvvSRi1UEm"

# CoinGecko API Base URL
COINGECKO_URL = "https://pro-api.coingecko.com/api/v3/"

# Exchange Details
EXCHANGE_NAME = "MEXC"
EXCHANGE_ID = "mxc"

# Function to fetch current Market Cap & FDV
def get_current_market_data(coin_id):
    url = f"{COINGECKO_URL}coins/{coin_id}?x_cg_pro_api_key={API_KEY}"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        market_cap = data.get("market_data", {}).get("market_cap", {}).get("usd", None)
        fdv = data.get("market_data", {}).get("fully_diluted_valuation", {}).get("usd", None)
        volume24h = data.get("market_data", {}).get("total_volume", {}).get("usd", None)
        return market_cap, fdv, volume24h
    except Exception as e:
        print(f"Error fetching current market data for {coin_id}: {e}")
        return None, None, None

# Function to fetch Order Book Depth (±2%) from Bybit
def fetch_depth(coin_id):
    url = f"{COINGECKO_URL}coins/{coin_id}/tickers?exchange_ids={EXCHANGE_ID}&depth=true&x_cg_pro_api_key={API_KEY}"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        tickers = data.get("tickers", {})
        if tickers:
            # Get the first ticker for the coin
            ticker = tickers[0]
            bid_ask_spread = ticker.get("bid_ask_spread_percentage", None)
            depth_plus_2 = ticker.get("cost_to_move_up_usd", None)
            depth_minus_2 = ticker.get("cost_to_move_down_usd", None)
        
            return bid_ask_spread, depth_plus_2, depth_minus_2
        return None, None, None
    except Exception as e:
        print(f"Error fetching depth data for {coin_id}: {e}")
        return None, None, None
        
    # try:
    #     response = requests.get(endpoint, params=params, headers=headers)
    #     response.raise_for_status()  # Raise an error for non-2xx responses
    #     return response.json()
    # except requests.exceptions.RequestException as e:
    #     print(f"Error fetching data: {e}")
    #     return None

# Function to fetch categories of a coin
def get_coin_categories(coin_id):
    url = f"{COINGECKO_URL}coins/{coin_id}?x_cg_pro_api_key={API_KEY}"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        return ', '.join(data.get("categories", []))
    except Exception as e:
        print(f"Error fetching categories for {coin_id}: {e}")
        return "Unknown"


# Main function to fetch & compile data
# def fetch_and_save_data():
#     print("\n🚀 Fetching data...")

# Main function to fetch & compile data
def main():
    # List of coin_ids
    coin_list = [
    'bitrock',
'bancor','nunet','hathor','guildqb-token','voxies','levana-protocol','league-of-kingdoms','de-fi','turbo','solana-social-explorer','friend3','taikai','catton-ai',
'maneki','arweave','bficoin','status','bakerytoken','swash','ix-swap','roam-token','$ever','handy','atua-ai','mythos','coti-governance-token','multi-asset-investment-vehicle',
'ooki','dforce-token','boson-protocol','skai','dolz-io','ubix-network','smart-valor','apenft','gptverse','aleo','cats-2','fish-cat','stakecube','berry',
'inspect','attarius','everipedia','layerium','griffain','neutron-3','toad','seed-3','morra','mubarakah','reserve-rights-token','iris-token-2','xpla','ideaology',
'trustinweb3','axol','the-emerald-company','nirvana-chain','e4c','napoli-fan-token','qlindo','hiro','kadena','phoenic-token','dov','injective-protocol','etherland',
'fio-protocol','hifi-finance','bst-chain','rock-4','lambda','melania-meme','artizen','ref-finance','obot','ondo-finance','dkargo','billionview','libra-incentix',
'kangamoon','sabai-ecovers','konnektvpn','security-token-offering','barnbridge','weebs','sylo','v-systems','trustfi-network-token','dogwifhat-eth','catizen',
'chronos-worlds-sphere','artrade','velo','gari-network','livepeer','mongcoin','oraichain-token','rizo','ethena','polyhedra-network','venture-mind-ai','harold',
'fly','convergence','blockchain-bets','honeyfun-ai','icon-x-world','moonwell-artemis','soex','ellipsis-x','merlin-chain','donald-tremp','pythia','french-connection-finance',
'polker','troll','airight','syscoin','money-dogs','tevaera','lee','kernel-2','kiteai','tajir-tech-hub','wodo-gaming','celer-network','agentsgpt','sui','nexo',
'beauty-bakery-linked-operation-transaction-technology','nya','puss','web3-ton-token','physis','akuma-inu','first-digital-usd','blocx-2','omisego','ergo','phnix',
'ainu-token','neurashi','hatom','metahorse-unity','sensay','maverick-protocol','arix','settled-ethxy-token','hemule','berachain-bera','hip','sei-network','power-ai',
'nexacoin','ginnan','gains','k21','zebu','aura-on-sol','bvm','lester','baanx','heima','netzero','based-froc','cockcardano','paraswap','chirpley','tao-inu','coreum',
'stool-prisondente','openocean','algorand','satoshisync','blocery','tux-project','gameswift','nereus-token','akitavax','swell-network','bluzelle','kat','ravencoin',
'kalichain','escoin-token','domin-network','vidt-dao','snap-2','aipump','bananatok','chonky','chiliz','vai','rex-3','dohrnii','lithium-finance','baby-bitcoin-2',
'aixbt','magic','zoo','open-loot','nodle-network','cosmos','auto','vice-2','billion-dollar-cat-runes','bicity-ai-projects','nuls','fanc','definity','melon','sin',
'verasity','cat','web3shot','nimbus-network','popcat','trava-finance','taboo-token','ss20','cookie','lovebit','mars-3','secretum','smardex','ispolink','stooges',
'ponke','peaq-2','bnc','milli-coin','rocki','common-wealth','wrapped-ncg','carbon-browser','deeper-network','naga','katana-inu','libra-5','enfineo','finceptor-token',
'gummy','santos-fc-fan-token','ags','osol','ecash','heurist','form','bertram-the-pomeranian','decubate','lion-token','bnbxbt','defrogs','parsiq','slp','ethereum-pow-iou',
'laika-ai','yay-games','avaocado-dao','@doge','squidgrow-2','klever','iustitia-coin','ztx','keep3rv1','fanton-token','sosovalue','cryptokki','eesee','alien-worlds',
'renewable-energy','vitreus','step-app-fitfi','poolz-finance-2','keke','$myst','kai','aiden-labs','arpa','rocket-pool','arkadiko-protocol','aree-shards','starknet','rai','baked','ancient8','gmt-token',
'ripple','altered-state-token','zeroswap','cryptify-ai','cocoro','funfi','aurora-dao','doginme','hold','khaokheowzoo','flamingo-finance','aleph','hosky','radiant',
'tokenbot-2','goldbrick','subquery-network','ai-agent-layer','proton','paris-saint-germain-fan-token','mfercoin','monero','sushi','consciousdao','captainbnb','swipe','agii','eliza','hamster-kombat','canxium','karate-combat','aivalanche-defai-agents',
'revv','handshake','onion','aergo','legends-of-elysium','domi','pirate-chain','og-fan-token','gains-network','xion-2','zoid-pay','phavercoin','jasmycoin','veloce-vext','pwr','virtue-poker','amber','ola','trailblaze','grass',
'deri-protocol','nuco-cloud','elys-network','chainx','metars-genesis','imaginary-ones','artyfact','alpha-4','zex','aiakita','pooh','sacabam','onecoinbuy','chex-token',
'djt','skale','bobo','xcad-network','lumoscoin','anime','skpanax','laqira-protocol','ai-code','pepe-unchained','valencia-cf-fan-token','jito-governance-token','cere-network','morpho',
'mbd-financials','sakura-united-platform','evmos','axo','melania-meme','$elon','mubarak','iron-stablecoin','duko','game7','bsc-station','navx','jam','luckycoin',
'electric-vehicle-direct-currency','mantra-dao','dogeai','chumbai-valley','hny','bone-bone','alpine-f1-team-fan-token','your-ai','npc-on-solana','functionland',
'thorchain','bad-coin','sui-depin','ridotto','aipad','slash-vision-labs','expert_money','babybonk','spell-token','nkn','genopets','freedom-2','wfi','chain-2',
'cornucopias','pingo','destra-network','lista','alvey-chain','mystery-2','swarm-bzz','amp-token','reborn-2','super-anon','token-metrics-ai','polis','befe','eden',
'virtual-protocol','0x','exosama-network','ordinals','spx6900','game-tree','alephium','fuse-network-token','udao','stobox-token','trace-network-labs','syncvault',
'minima','walrus-2','games-for-a-living','asm','eurite','mister-miggles','starrynift','paxe','bb','ready','effect-ai','gmx','iostoken','renq-finance','radicle',
'mine-btc','milady-meme-coin','lords','orangedx','kernel-2','wuffi','baby-sora','vempire-ddao','bugscoin','arc','seamless-protocol','neot','banana-for-scale-2',
'uprock','omom','carnomaly','casper-ai','xor','smell','billy','nodewaves','splash-trade','edelcoin','eva','flare-networks','jerrywifhat','chain-2','big-tom',
'everclear','spacecatch','chirppad','elixir-token','netvrk','smartworld-global','maker','solv-protocol','amo','ethereum-name-service','stake-link','stakestone',
'coinbarpay','landx-governance-token','vulcan-forged','turbo','tominet','snek','alpa','acquire-fi','r-games','pip','market-maverick','guru','hnb-protocol',
'tunachain','quantum-resistant-ledger','everton-fan-token','wayfinder','paw','bitscrunch-token','blocksquare','onfa','inter-milan-fan-token','kula','dejitaru-tsuka',
'star','redbelly-network-token','big-data-protocol','gamee','the-unfettered-souls','witch-token','cosmos','coca','windfall-token','mcoin-2','blendr-network',
'bxn','unice','beta','ultima','roolz','fu','unizen','reef','googles','grand-base','sui-plop','ethereum-classic','stohn-coin','deapcoin','bob','living-the-dream',
'wemix-token','newscrypto-coin','bitcoinbam','golfin','revomon-2','tamadoge','kibble-2','cryowar-token','illuvium','worldcoin-wld','stratos','taskbunny',
'welsh-corgi-coin','truflation','trade-leaf','ftx-token','aevo-exchange','bilira','slingshot-2','kiboshib','chwy','neiro','stellar','sol-cat','autonolas','moby',
'orca','zuzalu','supra','usdm-2','grok-6','stellar','kryll','limocoin-swap','tradetomato','spacepi-token','kango','cap-2','och','uxlink','aave','fracton-protocol',
'redx','bitcoin-cats','cheems','haha','gunz','pawswap','frax-share','polkastarter','pivn','hom','slerf','humans-ai','sardis-network','media-licensing-token',
'solo','vertus','znd-token','creditcoin-2','pump','standard-protocol','alice','convex-finance','dfyn-network','fartcoin','pi-network-dog','planet-token',
'honk','panther','dtravel','auki-labs','trac','pancakeswap-token','saga-2','usual','lazio-fan-token','ledgity-token','bityuan','bitcat','near','abi','the-graph',
'sauce','linqai','lithosphere','choise','ai-analysis-token','krest','autonomous-virtual-beings','pem','amc','dasha','elon-mars','paid-network','aios-foundation','avc',
'egg','nodecoin','vine','lympid','osmosis','karlsen','bitrise-token','retardio','azit','hopr','titan-3','six-sigma','kaia','notai','fetch-ai','nillion','ronin',
'squad','beam','elk-finance','nfprompt-token','kava','cryptogpt','massa','car-2','juice-2','preon-star','uma','$monky','trakx','port3-network','plume','centrality',
'blastup','unit-00-rei','qtum','seraph','xels','memefi-2','baby-bnb','berafi','big-time','solidus-aitech','qai','1inch','lightlink','machina','waves','dymension',
'aimonica-brands','open-meta-city','toucan-protocol-base-carbon-tonne','stronghold-token','terraport','mei-solutions','airtor-protocol','soon-2','lever','agro-global',
'goats-2','shrub','gaia-everworld','my-lovely-coin','shong-inu','jetfuel','xraders','leox','fwog','chainge-finance','carbify','@doge','crypto-ai-robo','steem',
'jet','nolus','aped','lol-3','zebec-network','renzo','zeta','usd-coin','5ire','kripto','analos','artfi','chax','chain-talk-daily','wave','juno-network','icrypex-token',
'fyde','ape-and-pepe','chain4energy','brainedge','creo-engine','kiloex','snapmuse-io','ox-fun','$three','lobo','prometeus','wall-street-pepe','seraph','darkshield',
'dog-3','sunwukong','sonic-4','newm','pnut','omnia','rekt','dao-maker','sentient-ai','redbelly-network-token','rally-2','1ex','bonfida','only1','stakestone','chia',
'route','neurai','shiden','infiblue-world','vyvo-smart-chain','tether-gold','quant-network','cow','manchester-city-fan-token','based-father-pepe','unlend-finance',
'eywa','k-pop-click-coin','humanode','lingo','neos-ai','constellation-labs','broccoli-5','netmind-token','obi-real-estate','meverse','souni-token','blackcardcoin',
'unit0','kamala-horris','mochi-thecatcoin','pendle','bitcicoin','lif3','ajuna-network-2','libertum','$man','dose-token','liquity','alfa-romeo-racing-orlen-fan-token',
'particle-network','farm','ski-mask-cat','spookyshiba-2','ai-network','zano','spain-national-fan-token','creta-world','harambe-ai','avery-games','gasp-2','mind-network',
'ictech','instadapp','moviebloc','klima-dao','paws','props','natix-network','script-network','ponchiqs','connect-token-wct','origyn-foundation','gluteus-maximus-by-virtuals',
'blnd','eml-protocol','nft-combining','pelfort','dione','public-meme-token','halo-2','tenet-1b000f7b-59cb-4e06-89ce-d62b32d362b9','boba','aerobud','mcdex','supra',
'deepfakeai','wolf','radix','safepal','sato','voi-network','ryo','wat','moonray','hashai','realio-network','nigella-chain','looksrare','synfutures','major','vestate',
'suai','houdini-swap','liberland-lld','ftx-token','commune-ai','vita-inu','suku','thetan-arena','srx','sai','zeebu','manta-network','zelwin','vow','book-of-ethereum',
'yolo','nillion','nerox-ai','sidus','omni','rsic','token-in','rose','songbird-finance','wisdomise','diam','joe','memhash','sundog','nvirworld','taiko','moonedge',
'stfx','obt','mad','osaka-protocol','music-protocol','cratos','rss3','bitget-token','alibabacoin','industry-sonic','origin-protocol','wall-street-memes','lingo',
'ekta-2','chirp-token','zignaly','human-protocol','gunz','vethor-token','vinuchain','hypercomic','lf','dynex','shieldeum','suncat','attila','realgoat','just',
'ailayer-token','orbofi-ai','argocoin-2','vanar-chain','shiba','gptplus','ovr','solvex-network','lukso-token-2','memdex100','fullsend-community-coin','nexade','max',
'raydium','gme','tokenize-xchange','gram-2','pell-network-token','dedacoin','lumia','miner-arena','apollox-2','unleashclub','xterio','memes-ai','dingocoin','zer',
'hydra','woo-network','tc','floki','stage','$fartboy','ai16z','mx-token','anvil','mpaa','neuron','azcoiner','banana','nomoex-token','bubb','lion-cat','bittorrent',
'apex-4','jetton','mbx','xyro','celo','tokenclub','uponly-token','particle-network','sun-token','soltradingbot','axiome','pikachu','tectum','zklink','x-project-erc',
'xdce-crowd-sale','rejuve-ai','rillafi','story-2','hive-ai','bellscoin','sovrun','ben-the-dog','moon-app','kapital-dao','rai','binancecoin','aipocalypto','safe',
'plume','dash','ozone-chain','baby-elon','zero1-labs','super-zero','kima','thrupenny','ultima','omni','mtl','rarible','pyth-network','ao-computer','moon','hedera-hashgraph',
'loom','unium','ordiswap-token','apron','galaxis-token','snpit-token','pippin','si','aia','peercoin','hotkeyswap','kitten-haimer','athenax9','zksync-id','tatsu',
'telos','ritestream','pixelverse-xyz','six-network','ambire-wallet','ethervista','neutaro','gull','renta-network','hypercycle','multibit','monero','layer3','balancer',
'marcopolo','raydium','eigenpie','joule-2','imgn-labs','saakuru-labs','australian-safe-shepherd','multi-universe-central','moew','elon4afd','plena','eigenlayer',
'cropbytes','pogai','pell-network-token','npc','veritas','osmi','rocketx','pointpay-2','pando','xwp','connect-token-wct','por','scotty','fear','navi','paws','tetsuo-coin',
'iexec-rlc','uquid-coin','abond','pepe','genesys','fsn','chillax','kryptonite','kingaru','goplus-security','xana','io','flux','biconomy','uno','oak-network','w3gg',
'vee',
'mog',
'nuts',
'mobix',
'flock-2',
'skull-of-pepe-token',
'tia',
'tanpin',
'abc',
'arkefi',
'phil',
'rod-ai',
'paysenger-ego',
'seda-2',
'paal-ai',
'trias-token',
'zelix',
'legacy-token',
'smog',
'secret',
'robofi-token',
'eos',
'peng',
'xxcoin-2',
'ape-4',
'fbx',
'quantlytica',
'life-2',
'hyperskids',
'doge',
'dextf',
'sakai-vault',
'groove',
'pain',
'gamium',
'levva-protocol',
'nym',
'camelot-token',
'ceek',
'ariva',
'zksync',
'zchains',
'strike',
'orbital7',
'stp-network',
'torsy',
'3-kingdoms-multiverse',
'canto',
'pepe',
'b3',
'across-protocol',
'runesterminal',
'active-token',
'qopro',
'hive',
'swarms',
'project-ailey',
'storm-warfare',
'y8u',
'mass-vehicle-ledger',
'ronaldinho-coin',
'modern-innovation-network-token',
'invest-zone',
'volumint',
'wexo',
'arca',
'suiswap',
'euler',
'financie-token',
'dogs-2',
'eos',
'connex',
'dechat',
'360noscope420blazeit',
'dexe',
'3dpass',
'tonny',
'alon',
'archloot',
'metis-token',
'xspectar',
'kine-protocol',
'cat-in-a-dogs-world',
'aihub',
'aventis-metaverse',
'babb',
'kasta',
'form',
'utrust',
'gamer-tag',
'npc',
'adshares',
'zircuit',
'ecoterra',
'leopold',
'unmarshal',
'bullbear-ai',
'islamic-coin',
'decentrawood',
'neurochainai',
'toshi',
'elon-trump-fart',
'mixin',
'sweatcoin',
'polydoge',
'stability-world-ai',
'ready-to-fight',
'pump',
'colle-ai',
'internet-computer',
'avail',
'koyo-6e93c7c7-03a3-4475-86a1-f0bc80ee09d6',
'ubxs-token',
'forward',
'fomo-3',
'pumpai',
'tubes',
'corn-3',
'token',
'why',
'hashflow',
'flayer',
'decred',
'gamezone',
'cyberconnect',
'gmt',
'aa',
'nexum',
'orderly-network',
'upcx',
'henjin-ai',
'winr-protocol',
'outer-ring',
'solama',
'mina-protocol',
'uwon',
'cybonk',
'derp',
'octaspace',
'stmx',
'bloxies-coin',
'reality-metaverse',
'polka-city',
'mumu',
'mass',
'ultron',
'alexgo',
'izumi-finance',
'crt-ai-network',
'bongo-cat',
'work',
'mon-protocol',
'she-rises',
'tico',
'sci-hub',
'telcoin',
'network3',
'tcg-verse',
'lamina1',
'numogram',
'medifakt',
'waves',
'carv',
'gt-protocol',
'honeyland-honey',
'clips',
'republik',
'gofundmeme',
'tomarket',
'gpus',
'ivendpay',
'basedai',
'ordify',
'tokocrypto',
'walk',
'qbx',
'aimedis-new',
'pnut',
'inverse-finance',
'omniflix-network',
'archethic',
'jambo',
'hedera-hashgraph',
'trillioner',
'interlay',
'internet-computer',
'homer',
'graphlinq-protocol',
'fasttoken',
'edexa',
'energy-web-token',
'sqd',
'portal-2',
'smiley-coin',
'sedra-coin',
'serum',
'alium-finance',
'the-winkyverse',
'wen-4',
'cheqd-network',
'zcoin',
'got-guaranteed',
'4everland',
'yield-guild-games',
'zilliqa',
'shido-2',
'openfabric',
'heroes-of-mavia',
'yuli',
'the-mars',
'adventure-gold',
'changex',
'unipoly',
'satoshivm',
'apex-token-2',
'genomesdao-genome',
'swingby',
'play-to-create',
'primex-finance',
'altura',
'genomefi',
'mode',
'venice-token',
'safemars-protocol',
'parex',
'kamino',
'mind-ai',
'fncy',
'dar-open-network',
'yearn-finance',
'flock-2',
'senso',
'feg',
'wrapped-nxm',
'kermit-cc0e2d66-4b46-4eaf-9f4e-5caa883d1c09',
'syrup',
'edog',
'assetmantle',
'niza-global',
'green-shiba-inu',
'aave',
'ai-nexus',
'biometric-financial',
'berachain-bera',
'vapor-wallet',
'songbird',
'scotcoin-2',
'xrpaynet',
'stat',
'ethos',
'koii',
'symbol',
'sosovalue',
'pivx',
'real-smurf-cat',
'crw',
'nexusmind',
'abey',
'ethena',
'shadow-wizard-money-gang',
'dua-token',
'umbrella-network',
'hive_dollar',
'kusama',
'oxya-origin',
'plastichero',
'mcdull',
'lake',
'taocat-by-virtuals',
'hive-intelligence',
'swftcoin',
'kommunitas',
'alchemy-pay',
'arcana-token',
'xbanking',
'smolecoin',
'ant',
'qubic-network',
'wagmicatgirlkanye420etfmoon1000x',
'dodo',
'pork',
'qubic-network',
'plyr-l1',
'lava',
'theta-fuel',
'ampleforth-governance-token',
'cmcx',
'offcial-mascot-of-the-holy-year',
'cetus-protocol',
'elixir-finance',
'orange',
'hello-labs',
'xerc20-pro',
'sui-rwa',
'affyn',
'pump',
'habibi',
'openleverage',
'coinweb',
'swarmnode-ai',
'forkast',
'hydro-protocol-2',
'platform-of-meme-coins',
'edu3labs',
'imgnai',
'joy',
'messier',
'dexcheck',
'sols',
'assai',
'xelis',
'toncapy',
'brn-metaverse',
'trumpius-maximus',
'tomwifhat',
'baby',
'amepay',
'xp',
'ethdydx',
'suipad',
'zigap',
'blast',
'stafi',
'baby',
'beercoin-2',
'edu-coin',
'blur',
'bella-protocol',
'catboy-3',
'emoneytoken',
'fishwar',
'one',
'credbull',
'xswap-2',
'azuro-protocol',
'nibiru',
'koi-4',
'worldbrain-coin',
'musk-it',
'chimpzee-chmpz',
'gam3s-gg',
'neon',
'laika',
'vela-token',
'holotoken',
'aicore',
'cypherium',
'saros-finance',
'destra-network',
'max',
'bitcoin-2',
'iskra-token',
'sao-paulo-fc-fan-token',
'crm',
'peipeicoin-vip',
'bnb-agents',
'aavegotchi',
'lofi-2',
'drop',
'megalink',
'resistance-dog',
'upland',
'playbux',
'the-root-network',
'kaito',
'gui-inu',
'covenant-child',
'casper-network',
'agridex-governance-token',
'cult',
'botify',
'unifi-protocol-dao',
'metados',
'wadzcoin',
's-c-corinthians-fan-token',
'rnt-token',
'xcarnival',
'platon-network',
'staked-ether',
'bho-network',
'orbitt-pro',
'aixbt',
'retik-finance',
'elis',
'venus',
'insurace',
'pika',
'pha',
'tribe-3',
'freedom-3',
'quick',
'musmecoin',
'marvellex-classic',
'vivi-coin',
'trust-wallet-token',
'cybro',
'octavia',
'fanfury',
'gochu',
'rixen-finance',
'moonbeam',
'dinero-2',
'egochain',
'catana',
'$dice',
'binancecoin',
'layerzero',
'rif-token',
'space-nation-oikos',
'dojo-protocol',
'catecoin',
'ultiverse',
'partisia-blockchain',
'avalox',
'mansory-token',
'coin98',
'bedrock-token',
'neighbourhoods',
'stonks-4',
'roco-finance',
'wilder-world',
'threshold-network-token',
'yfii-finance',
'suiai',
'hashkey-ecopoints',
'lynx',
'din',
'blockdrop',
'bazaars',
'metaplex',
'ankr',
'colony',
'sigma',
'land',
'lbry-credits',
'storj',
'meme-ai-coin',
'msquare-global',
'mind-network',
'metamui',
'seedify-fund',
'playa3ull-games-2',
'vara-network',
'popcat',
'exverse',
'misbloc',
'his-name-gort',
'the-husl',
'bsx',
'tapswaptoken',
'laos-network',
'ecomi',
'tron-bull-coin',
'clash',
'mcontent',
'mars4',
'anchor-protocol',
'zerebro',
'goracle-network',
'opulous',
'pochita',
'privateai',
'gohome',
'jelly-my-jelly',
'iguverse-igu',
'unicorn-fart-dust',
'agixt',
'tri-sigma',
'unio-coin',
'army',
'htx-dao',
'wizzwoods-token',
'klever-finance',
'xai',
'kaizen',
'vidt-dao',
'kishu-inu',
'lina',
'mira-2',
'hero-blaze-three-kingdoms',
'jaseonmun',
'perpetual-protocol',
'ethereum-name-service',
'dogex-2',
'passage',
'cpucoin',
'nux',
'vechain',
'orders-exchange',
'octopus-network',
'cocos-bcx',
'weco',
'soarchain',
'mx-token',
'pstake-finance',
'wusd',
'self-chain',
'kujira',
'camino-network',
'tmns',
'gamercoin',
'giant-mammoth',
'sac-daddy',
'liquidium-token',
'paxos-standard',
'duelnow',
'virtual-protocol',
'hi-dollar',
'world-mobile-token',
'aleph-zero',
'yaka',
'gala',
'crypto-hunters-coin',
'charged-particles',
'book-2',
'radio-caca',
'chromium-dollar',
'metaverse-face',
'minativerse',
'kin',
'propchain',
'shadow-node',
'mother-iggy',
'covalent-x-token',
'ai16z',
'zephyr-protocol',
'mist',
'akropolis',
'simpson',
'ssv-network',
'derace',
'love-moli',
'wrapped-axelar',
'blade-2',
'tema',
'oort',
'hyve',
'peaq-2',
'leeds-united-fan-token',
'xhype',
'qi',
'republic-protocol',
'merge',
'lyvely',
'hasbulla-s-cat',
'hege',
'shroomy',
'tenup',
'cook',
'catheon-gaming',
'unicorn-ultra',
'ta-da',
'rabi',
'defai',
'alt',
'xodex',
'pastel',
'soil',
'stonks-5',
'magiccraft',
'suicy-the-seal',
'zenqira',
'dusk-network',
'sui-desci-agents',
'ondo-finance',
'puffer-finance',
'vite',
'pepecoin-2',
'cros',
'patex',
'spore',
'memes',
'cross-the-ages',
'kingdom-game-4-0',
'marlin',
'wesendit',
'lumi',
'hq',
'maga-trump',
'wojak',
'ether-fi',
'hero',
'jasmycoin',
'allianceblock-nexera',
'meai',
'dongdaemun-token',
'areon-network',
'infinitar-governance-token',
'sapiens',
'ecomi',
'aeternity',
'starlink',
'synternet-synt',
'kiloex',
'$gini',
'fognet',
'gpt-wars',
'medicle',
'sturdy',
'zulu-network',
'seiyan',
'relation-native-token',
'oec-token',
'near',
'fruits',
'cat-gold-miner',
'walrus-2',
'dego-finance',
'odos',
'fc-porto',
'flamengo-fan-token',
'meter',
'waffles',
'velar',
'defi-kingdoms',
'golcoin',
'playdapp',
'minto',
'bonk',
'hund',
'kilt-protocol',
'flow',
'sillynubcat',
'crowns',
'rivalz-network',
'hat',
'mina-protocol',
'bsv',
'weway',
'analog',
'quai-network',
'gorilla',
'reform-dao',
'pepecat',
'aleph-zero',
'pitbull',
'weatherxm-network',
'xrp-healthcare',
'blue-inbetweeners',
'meson-network',
'unirouter',
'blub','degen-base','clearpool','radiant-capital','serenity-shield','ark','polimec','vanilla-2','openex-network-token',
'epay-2','nav','orchid-protocol','wpay','spice-3','freebnk','numeraire','ethereumfair','reflect-base','parcl','algorand','push','ripples','xrp-classic-new',
'chaingpt','yieldbricks','fandomdao','hedera-guild-game','solanium','k9-finance-dao','scx','victoria-vr','ithaca-protocol','coldstack','pre-retogeum','nyan','astros','havven','coti','miu','zkfair',
'moon','kaito','satoxcoin','salad','joltify','grindery-x','undeads-games','edge','doge-eat-doge','talent-protocol','apf-coin','paladeum','bitdca','hoppy-meme','sexone',
'binary-holdings','ski-mask-dog','harambe','rbx-token','karrat','qorbi','senate','kenka-metaverse','omax-token','we-love-t','ripple','legend','oraidex','soonchain',
'compound-governance-token','ong','zetrix','torum','limewire-token','stargate-finance','render-token','collaterize','shifu','bobacat','headstarter','vectorspace',
'fartcoin','api3','flatqube','space-3','sanctum-2','okb','rats','perry','first-reply','index-cooperative','bistroo','venom','anduschain','borealis','aastoken',
'helium','eldarune','pocket-network','axie-infinity','hapi','odin-3','modclub','mazze','kaspy','bullperks','block','electra-protocol','nikolai','maiar-dex','phantom-of-the-kill-alternative-imitation-oshi','trump',
'uni','spx6900','stacktical','ondo-defai','bounty-temple','masa-finance','pongo','q-protocol','bizauto','logx','xusd','helium-mobile','foxsy-ai','taraxa','socialgrowai','mey-network',
'ayin','meter-stable','gamer-arena','fetch-ai','pudgy-penguins','yne','neversol','dogecoin20','unibot','dai','hamster','moonriver','xo-protocol','clay','refund','badger-dao','neur-sh','wayfinder','raini-studios-token',
'bubblefong','immutable-x','ai-voice-agents','giko-cat','dtec-token','myria','ninja-squad','hypergpt','kucoin-shares','shib2','chainaware-ai','karura','treecle','hooked-protocol','ghoad','pulsara','blueshift','ndc','acala',
'arkham','dyor','elysia','navix','wax','carbon-emission-blockchain','crust-network','digitalbits','corn-3','kaif','bullysoltoken','boxbet','loopnetwork','veil','plgnet','pibble','bitshares','diamond-castle','high','zkswap-finance','xsl-labs',
'mubarak','nodeai','nervos-network','uni','exorde','shiboo','book-of-meme','pi-network','perion','hydranet','roseon','agenda-47','$myro','mojo','wasder','clustr','befi-labs','all-in','int-os','zcash',
'astra','africarare','defactor','send-token-2','welf','zeuspepesdog','auction','tia','indigo-dao-governance-token','whitebit','pixer-eternity',
'magaverse','avalaunch','nft-workx','wexo','hall-of-legends','duck','stride','dmail-network','samoyedcoin','mancium','midle','swisscheese','hivello','wagmi-game-2','decentralized-etf','g-2','bscpad',
'coq-inu','cortex','the-winners-circle','playzap','realio-network','cat-dog','token-pocket','dentnet','von',
'chaingpt','optcm','kolz','koi','gather-2','pax-gold','versity-2','ami','math','agoras-currency-of-tau','football-world-community','apecoin','virtualdaos',
'evrynet','kaia','global-commercial-business','kyber-network-crystal','dvision-network','super-trump','mintlayer','sui','earnm','neo','deep','bitbrawl','vana','elrond-erd-2','injective-protocol','clore-ai','altava','metagalaxy-land',
]

    results = []

    for coin_id in coin_list:
        print(f"Fetching data for: {coin_id}")
        time.sleep(0.3)

        # Get Current Market Cap & FDV
        market_cap_today, fdv_today, volume24h = get_current_market_data(coin_id)

        # Fetch Order Book Depth & Liquidity Metrics
        bid_ask_spread, depth_plus_2, depth_minus_2 = fetch_depth(coin_id)

        # Fetch Coin Category
        category = get_coin_categories(coin_id)


        # Store data in a dictionary
        results.append({
            "Exchange": EXCHANGE_NAME,
            "Category": category,
            "Token CEX": coin_id,
            "Market Cap Today": market_cap_today,
            "FDV Today": fdv_today,
            "Depth +2%": depth_plus_2,
            "Depth -2%": depth_minus_2, 
            "Bid Ask Spread Percentage": round(bid_ask_spread, 2) if bid_ask_spread else "N/A",
            "24H Volume (USD)": volume24h
        })

    # Convert results to DataFrame
    df_output = pd.DataFrame(results)

    # Save the data to a new Excel file with a timestamp in the filename
    output_file = f"MexcData.xlsx"
    df_output.to_excel(output_file, index=False)

    print(f"✅ Data saved to {output_file}")

# Schedule the function to run daily at a specific time (e.g., 08:00 AM)
# schedule.every().day.at("08:00").do(fetch_and_save_data)

# print("⏳ Scheduler is running. Press Ctrl+C to stop.")

# Keep the script running indefinitely
# while True:
#     schedule.run_pending()
#     time.sleep(60)  # Check for scheduled tasks every 60 seconds

if __name__ == "__main__":
    main()
